# Generated by Django 3.0 on 2019-12-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=64)),
                ('flight_st_date', models.DateField()),
                ('flight_end_date', models.DateField()),
                ('flight_st_time', models.TimeField()),
                ('flight_end_time', models.TimeField()),
                ('flight_price', models.IntegerField()),
            ],
        ),
    ]
