# Generated by Django 3.0 on 2019-12-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_runtime', models.IntegerField()),
                ('movie_genre', models.CharField(max_length=255)),
                ('movie_rating', models.FloatField()),
            ],
        ),
    ]
